CREATE DATABASE TNCR;

USE TNCR;

CREATE TABLE MATERIAL(
    ID INT AUTO_INCREMENT NOT NULL,
    PRIMARY KEY (ID),
    NAME VARCHAR(64) UNIQUE NOT NULL,
    CODE VARCHAR(64) UNIQUE NOT NULL
);

CREATE TABLE ORIENTATION (
    ID INT AUTO_INCREMENT NOT NULL,
    PRIMARY KEY (ID),
    NAME VARCHAR(64) UNIQUE NOT NULL,
    CODE VARCHAR(64) UNIQUE NOT NULL
);

CREATE TABLE CARDINAL_POINT (
    ID INT AUTO_INCREMENT NOT NULL,
    PRIMARY KEY (ID),
    NAME VARCHAR(64) UNIQUE NOT NULL,
    CODE VARCHAR(64) UNIQUE NOT NULL
);

CREATE TABLE TECHNICAL_UNIT (
    ID INT AUTO_INCREMENT NOT NULL,
    PRIMARY KEY (ID),
    NAME VARCHAR(64) UNIQUE NOT NULL,
    CODE VARCHAR(64) UNIQUE NOT NULL
);

CREATE TABLE VARIABLE (
    ID INT AUTO_INCREMENT NOT NULL,
    PRIMARY KEY (ID),
    NAME VARCHAR(64) UNIQUE NOT NULL,
    CODE VARCHAR(64) UNIQUE NOT NULL,
    UNIT VARCHAR(64) NOT NULL
);

CREATE TABLE MONITORING_FREQUENCY (
    ID INT AUTO_INCREMENT NOT NULL,
    PRIMARY KEY (ID),
    FREQUENCY VARCHAR(32) UNIQUE NOT NULL
);

CREATE TABLE INSTRUMENT_TYPE
(
    ID   INT AUTO_INCREMENT NOT NULL,
    TYPE VARCHAR(64)        NOT NULL UNIQUE
);

CREATE TABLE WOUND
(
    ID   INT AUTO_INCREMENT NOT NULL,
    PRIMARY KEY (ID),
    NAME VARCHAR(64) UNIQUE NOT NULL,
    CODE VARCHAR(64) UNIQUE NOT NULL
);

CREATE TABLE BLOCK
(
    ID    INT AUTO_INCREMENT NOT NULL,
    PRIMARY KEY (ID),
    NAME  VARCHAR(64) UNIQUE NOT NULL,
    CODE  VARCHAR(64) UNIQUE NOT NULL,
    FLOOR INT                NOT NULL
);

CREATE TABLE ELEMENT_TYPE
(
    ID                INT AUTO_INCREMENT NOT NULL,
    PRIMARY KEY (ID),
    NAME              VARCHAR(64) UNIQUE NOT NULL,
    CODE              VARCHAR(64) UNIQUE NOT NULL,
    TECHNICAL_UNIT_ID INT                NOT NULL,
    FOREIGN KEY (TECHNICAL_UNIT_ID) REFERENCES TECHNICAL_UNIT (ID)
);

CREATE TABLE ELEMENT
(
    ID                INT AUTO_INCREMENT NOT NULL,
    PRIMARY KEY (ID),
    NAME              VARCHAR(64) UNIQUE NOT NULL,
    CODE              VARCHAR(64) UNIQUE NOT NULL,
    NUMBER            INT,
    ORIENTATION_ID    INT,
    FOREIGN KEY (ORIENTATION_ID) REFERENCES ORIENTATION (ID),
    CARDINAL_POINT_ID INT,
    FOREIGN KEY (CARDINAL_POINT_ID) REFERENCES CARDINAL_POINT (ID),
    ELEMENT_TYPE_ID   INT,
    FOREIGN KEY (ELEMENT_TYPE_ID) REFERENCES ELEMENT_TYPE (ID),
    BLOCK_ID          INT,
    FOREIGN KEY (BLOCK_ID) REFERENCES BLOCK (ID)
);

CREATE TABLE ELEMENT_MATERIAL
(
    ELEMENT_ID  INT           NOT NULL,
    FOREIGN KEY (ELEMENT_ID) REFERENCES ELEMENT (ID),
    MATERIAL_ID INT           NOT NULL,
    FOREIGN KEY (MATERIAL_ID) REFERENCES MATERIAL (ID),
    PRIMARY KEY (ELEMENT_ID, MATERIAL_ID),
    REMARKS     VARCHAR(1024) NOT NULL
);

CREATE TABLE MATERIAL_RANGE
(
    MATERIAL_ID INT NOT NULL,
    FOREIGN KEY (MATERIAL_ID) REFERENCES MATERIAL (ID),
    VARIABLE_ID INT NOT NULL,
    FOREIGN KEY (VARIABLE_ID) REFERENCES VARIABLE (ID),
    PRIMARY KEY (MATERIAL_ID, VARIABLE_ID),
    MIN_RANGE   FLOAT,
    MAX_RANGE   FLOAT
);

CREATE TABLE WOUND_ELEMENT
(
    WOUND_ID        INT NOT NULL,
    FOREIGN KEY (WOUND_ID) REFERENCES WOUND (ID),
    ELEMENT_TYPE_ID INT NOT NULL,
    FOREIGN KEY (ELEMENT_TYPE_ID) REFERENCES ELEMENT_TYPE (ID),
    MATERIAL_ID     INT NOT NULL,
    FOREIGN KEY (MATERIAL_ID) REFERENCES MATERIAL (ID),
    VARIABLE_ID     INT NOT NULL,
    FOREIGN KEY (VARIABLE_ID) REFERENCES VARIABLE (ID),
    PRIMARY KEY (WOUND_ID, ELEMENT_TYPE_ID, MATERIAL_ID, VARIABLE_ID)
);

CREATE TABLE INSTRUMENT_TYPE
(
    ID   INT AUTO_INCREMENT NOT NULL,
    PRIMARY KEY (ID),
    TYPE VARCHAR(64) UNIQUE NOT NULL
);

CREATE TABLE INSTRUMENT
(
    ID                      INT AUTO_INCREMENT NOT NULL,
    PRIMARY KEY (ID),
    NAME                    VARCHAR(64) UNIQUE NOT NULL,
    CODE                    VARCHAR(64) UNIQUE NOT NULL,
    MODEL                   VARCHAR(64),
    ASSET_CODE              VARCHAR(64)        NOT NULL,
    MONITORING_FREQUENCY_ID INT,
    FOREIGN KEY (MONITORING_FREQUENCY_ID) REFERENCES MONITORING_FREQUENCY (ID),
    BLOCK_ID                INT,
    FOREIGN KEY (BLOCK_ID) REFERENCES BLOCK (ID),
    INSTRUMENT_TYPE_ID      INT                NOT NULL,
    FOREIGN KEY (INSTRUMENT_TYPE_ID) REFERENCES INSTRUMENT_TYPE (ID)
);

CREATE TABLE INSTRUMENT_VARIABLE
(
    VARIABLE_ID   INT NOT NULL,
    FOREIGN KEY (VARIABLE_ID) REFERENCES VARIABLE (ID),
    INSTRUMENT_ID INT NOT NULL,
    FOREIGN KEY (INSTRUMENT_ID) REFERENCES INSTRUMENT (ID),
    PRIMARY KEY (VARIABLE_ID, INSTRUMENT_ID)
);

CREATE TABLE ALARM
(
    ID              INT AUTO_INCREMENT NOT NULL,
    PRIMARY KEY (ID),
    ELEMENT_ID      INT                NOT NULL,
    FOREIGN KEY (ELEMENT_ID) REFERENCES ELEMENT (ID),
    MATERIAL_ID     INT                NOT NULL,
    FOREIGN KEY (MATERIAL_ID) REFERENCES MATERIAL (ID),
    VARIABLE_ID     INT                NOT NULL,
    FOREIGN KEY (VARIABLE_ID) REFERENCES VARIABLE (ID),
    INSTRUMENT_ID   INT                NOT NULL,
    FOREIGN KEY (INSTRUMENT_ID) REFERENCES INSTRUMENT (ID),
    RAISED_DATE     VARCHAR(64)        NOT NULL,
    REASON_OF_RAISE VARCHAR(128)       NOT NULL,
    AVG_VALUE       FLOAT              NOT NULL,
    VARIANCE_VALUE  FLOAT              NOT NULL,
    FREQUENCY_ID    INT                NOT NULL,
    FOREIGN KEY (FREQUENCY_ID) REFERENCES MONITORING_FREQUENCY (ID)
);


CREATE TABLE WOUND_ALARM_ACTION
(
    ALARM_ID     INT           NOT NULL,
    FOREIGN KEY (ALARM_ID) REFERENCES ALARM (ID),
    WOUND_ID     INT           NOT NULL,
    FOREIGN KEY (WOUND_ID) REFERENCES WOUND (ID),
    ACTION_TAKEN VARCHAR(1024) NOT NULL
);



